development:
  adapter: postgresql
  database: bonfire_development
  username: andrewluna
  password:
  host: localhost
  port: 5432
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: sample_postgres_test
#   pool: 5
#   username: sample_postgres
#   password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: sample_postgres_production
#   pool: 5
#   username: sample_postgres
#   password:

