default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  database: bonfire_development
  username: andrewluna
  password:
  host: localhost
  port: 5432
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: sample_postgres_test
#   pool: 5
#   username: sample_postgres
#   password:

production:
  <<: *default
  database: bonfire_db_prod
  adapter: "postgresql"
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
