development:
  adapter: postgresql
  database: bonfire_development
  username: andrewluna
  password:
  host: localhost
  port: 5432
# test:
#   adapter: postgresql
#   encoding: unicode
#   database: sample_postgres_test
#   pool: 5
#   username: sample_postgres
#   password:

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['PGDATABASE'] %>
  pool: 5
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
